version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  model_backend:
    build:
      context: ./model_backend
    container_name: model_backend_container
    ports:
      - "8000:8000"

  web_backend:
    build:
      context: ./model_service
    container_name: web_backend_container
    ports:
      - "8080:8080"
    depends_on:
      - db
      - model_backend

  frontend:
    build:
      context: ./web_service/vue-frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - web_backend
