version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: titanic
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 30s
      timeout: 10s
      retries: 5

  model_backend:
    build:
      context: ./model_service
      dockerfile: Dockerfile.model_backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  web_backend:
    build:
      context: ./web_service/backend
      dockerfile: Dockerfile.web_backend
    environment:
      - MODEL_BACKEND_URL=http://model_backend:8000
    ports:
      - "8080:8080"
    depends_on:
      - model_backend
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./web_service/vue-frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      web_backend:
        condition: service_healthy

