stages:
  - build
  - setup
  - test

variables:
  POSTGRES_DB: test
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - ls -la  # List files to verify Dockerfile presence
    - cat Dockerfile  # Output Dockerfile content to verify
    - docker-compose build

setup:
  stage: setup
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker-compose up -d db
    - docker-compose up -d server
    - echo "Waiting for server to be ready..."
    - until curl -s http://127.0.0.1:8000; do echo "Waiting..."; sleep 5; done  # Use new port 8080

pytest:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker-compose exec server pip install -r requirements.txt
    - docker-compose exec server pytest tests/
  dependencies:
    - setup
  allow_failure: false
